import pygame
pygame.init()

dorm1 = pygame.mixer.Sound("sounds/dorm1.mp3")
dorm1 = pygame.mixer.Sound("sounds/dorm2.mp3")
casino = pygame.mixer.Sound("sounds/casino.mp3")
club = pygame.mixer.Sound("sounds/club.mp3")
gym = pygame.mixer.Sound("sounds/gym.mp3")
map = pygame.mixer.Sound("sounds/map.mp3")
map_back = pygame.mixer.Sound("sounds/map_back.mp3")
study = pygame.mixer.Sound("sounds/study.mp3")
disco_loop_1 = pygame.mixer.Sound("sounds/disco_loop_1.wav")
disco_loop_2 = pygame.mixer.Sound("sounds/disco_loop_2.wav")
disco_loop_3 = pygame.mixer.Sound("sounds/disco_loop_3.wav")
drink = pygame.mixer.Sound("sounds/drink.mp3")
jackpot = pygame.mixer.Sound("sounds/jackpot.wav")
theatre = pygame.mixer.Sound("sounds/theatre.mp3")
slot_machine_roll = pygame.mixer.Sound("sounds/slot_machine_roll.wav")
punch = pygame.mixer.Sound("sounds/punch-boxing-06-reverb-82202.mp3")
# strong_punch = pygame.mixer.Sound("sounds/strong_punch.mp3")